---
driver:
  name: docker
  hostname: cadf.ci.local
  use_sudo: false



provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: info
  formula: cadf
  grains:
    noservices: true
  state_top:
    base:
      "*":
        - cadf
  pillars:
    top.sls:
      base:
        "*":
          - cadf


verifier:
  name: inspec
  sudo: true

platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt-formulas:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu


suites:

  - name: default
    provisioner:
      pillars-from-files:
        cadf.sls: tests/pillar/init.sls


# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
